### ISSUE TITLE
[request] eslint plugin

### ISSUE THREAD

**Issue by goatandsheep** [mvdschee/web-accessibility#1]
**Is your feature request related to a problem? Please describe.**
I can't use npm to run the lint

**Describe the solution you'd like**
A second program that used the logic of this as an eslint plugin

**Describe alternatives you've considered**
None of the other HTML lints have the a11y linters yours has

**Comment by mvdschee** [comment]
@goatandsheep You're right you can't use NPM to run this, it only runs in Visual Studio Code as it uses the API for their editor. On your idea for an ESlint plugin, seems smart but not doable at this time, I still need to get this project out of its alpha stage.
