### ISSUE TITLE
Make sure all frames and iframes have a title attribute

### ISSUE THREAD

**Issue by ecerta** [mvdschee/web-accessibility#15]
**Is your feature request related to a problem? Please describe.**
Any time you have any kind of frame, it should have a title attribute with words inside. (Note, not a <title> element, a title attribute, as in <iframe title="Why You Should Make Issues on Github Video">).

**Describe the solution you'd like**
Add a check for the linter that any and all frames or iframes have a title attribute.

**Describe alternatives you've considered**
I just think it's within the power of a linter like this to check for it and it's an a11y requirement, so let's go for it.

**Additional context**
https://webaim.org/techniques/frames/

**Comment by mvdschee** [comment]
Thank you for the issue! It will be added in the next update :)

**Comment by mvdschee** [comment]
The linting for missing title attributes for `frames` and `iframes` has been implemented in version 0.2.4.
