### ISSUE TITLE
Option to disable semantically transparent elements highlight

### ISSUE THREAD

**Issue by Worie** [mvdschee/web-accessibility#17]
**Is your feature request related to a problem? Please describe.**
It's sometimes better to use `divs` for wrapper elements that are necessary to implement complex layouts, not every `div` or `span` is bad if used with concious.

**Describe the solution you'd like**
An option in preferences to disable/enable semantically transparent elements highlight about `Use semantic HTML5 or specify WAI-ARIA role`, or an option to disable this monit on particular chosen elements (if possible)

**Comment by mvdschee** [comment]
Seems like a reasonable option to have. I think I will add an option to disable the semantic highlight globally and one where you can disable it per file.

**Comment by Worie** [comment]
nice! thanks

**Comment by mvdschee** [comment]
I have added the option to disable the semantic HTML highlight for `span` and `div` in the settings. 
The settings you can change at: `File > Preferences > Settings > Extensions > Configuration`

I have added the disable and enable functionality to the To Do for the Major update. If this satisfies your request, I will close the issue 😃
