### ISSUE TITLE
Meta viewport recommendation of adding user-scalable displays after fix

### ISSUE THREAD

**Issue by joseph-kaainoa** [mvdschee/web-accessibility#21]
**Describe the bug**
For a viewport meta tag with content without user-scalable, it displays the "Enable piching to zoom.." recommendation.  After adding it to the content, the recommendation still shows.

**To Reproduce**
1. In an HTML file, have:
```html
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">
```
**Expected behavior**
Recommendation should not display once the user-scalable is added.

**Screenshots**
![2019-04-24 17_58_14-WebAccessibility VS Code Extension](https://user-images.githubusercontent.com/13756302/56703169-90c19000-66bc-11e9-950a-ddf79abb8b39.png)

**Visual Studio Code (please complete the following information):**
 - Version 1.34.0-insider (user setup)
 - Windows Version 10.0.16299.1087 

**Additional context**
Restarted VSCode several times after making the change.  Also disabled all the other extensions to verify it wasn't something that was colliding with another extension.

**Comment by mvdschee** [comment]
@joseph-kaainoa thank you for your thorough issue report. I believe it has something to do with the way I check for `whitespaces` between `user-scalable=` and `yes`. It will be fixed today!

**Comment by joseph-kaainoa** [comment]
Awesome job on the quick fix!

**Comment by mvdschee** [comment]
Version 0.2.6 is live which contains the fix for the issue. The update should be available in a couple of minutes in VS code :)
