### ISSUE TITLE
deprecated package 'path-is-absolute'

### ISSUE THREAD

**Issue by knostradamus** [mvdschee/web-accessibility#30]
I performed a diagnostic package search on this extension and found the following. 

Package has been deprecated
https://www.npmjs.com/package/path-is-absolute
This package is no longer relevant as Node.js 0.12 is unmaintained.

Is this package necessary?

Thank you for your time.

**Comment by mvdschee** [comment]
@knostradamus Thank you for taking the time to do an audit, it looks like it's from one of the packages called `glob` that is used by the extensions dependencies. I did some more digging and found out it's a know issue at `glob` but not sure when it will be resolved [node-glob pull 407](https://github.com/isaacs/node-glob/pull/407)

**Comment by knostradamus** [comment]
Thanks for the update. Should I close this? 
It seems like it's such a common library.
