### ISSUE TITLE
Support for Font Awesome <span> technique

### ISSUE THREAD

**Issue by HarryAdney** [mvdschee/web-accessibility#33]
The extension currently highlights a Font Awesome spans and <i> tags, expecting a role to be added, e.g.
`<span class="fa fa-phone pe-color pe-small-icon" role=></span>`

If the extension recognised, for instance, `aria-hidden='true` this would really save a lot of corrective development time.

I've tried adding roles to the spans, but this isn't necessarily a valid option.

**Comment by mvdschee** [comment]
He @HarryAdney I have implemented your request. With the latest update, you should not have any errors if you add `aria-hidden="true"` to your `span`
