### ISSUE TITLE
More and better linting in alt text

### ISSUE THREAD

**Issue by ecerta** [mvdschee/web-accessibility#6]
**Is your feature request related to a problem? Please describe.**
First, the linter currently flags a non-issue. Best practice for images of purely decorative text is an empty alt, like so: `<img src="decorative_scribble.png" alt="">`

Second, there's a lot of other bad alts that can be caught with their own tests, including:
- Crummy alts, like `alt="image"`
- Bad practice alt opening, like `alt="image of a white dog on a green couch"`. "image of," "picture of" etc. are not recommended for alt openings.
- Alt text that is too long. Most modern screen readers cut off reading alt text at 125 characters.

**Describe the solution you'd like**
Improvements to the image alt linter to account for these cases.

**Describe alternatives you've considered**
I suppose there's a question on whether these should all be grouped together in the validateImg function or broken out into separate tests, but I do think this would be a great addition either way.

**Additional context**
I'm already working on this! Hope I didn't jump the gun here. Also, more information on good alt text: https://webaim.org/techniques/alttext/

**Comment by mvdschee** [comment]
@ecerta It's indeed better to have those common mistakes like the cases you describe to be flagged as well. However, the reasons I accepted just one character as a valid option was that 1) I wanted people to be aware that they should make a descriptive alt text 2) I figured out how to link to resources they could read to help with making a descriptive alt text.

However, I haven't figured out how to insert a link in the error messages or if it's even possible.

Thanks for the link to the resource about alt texts, helps me out a lot and if you are willing to participate by writing those checks, I'm very grateful for that.

**Comment by ecerta** [comment]
Oh, one character might be a valid option, like if the image just shows the letter A (although "the letter A" might be better than just "A"). The kind of crummy alt text I was thinking of was "image" or "graphic." I can't find the blog post anymore but someone grepped through thousands of webpages and found the most common alt text was "image," which is no good.

As a side-note, if this passes it'll need a different example video, since it shows "image" being put in as alt text (I know it's just an example, but it's no good to show a passing example as something that'll be flagged by a different check).

**Comment by mvdschee** [comment]
I noticed the pull request a little late but it's a good solution for the alt text problem, I will do some local test cases and added it to the next update (with reverence to your GitHub page), and I will make sure there is a new suitable example.
