### ISSUE TITLE
Title check does not trigger when <head> is empty and right next to </head>

### ISSUE THREAD

**Issue by ecerta** [mvdschee/web-accessibility#8]
**Describe the bug**
The check to be sure there is a `<title>` attribute between `<head>` tags does not trip if the `<head>` tags are empty and right next to each other.

**To Reproduce**

**Expected behavior**
The linter should trip when `<header>` tags are empty and consecutive.

**Screenshots**
<img width="237" alt="consecutive opening and closing head tags with no title attribute. No linter underline." src="https://user-images.githubusercontent.com/6492662/50730393-951c6a00-111a-11e9-9cb5-feeb1fd1511d.png">

Note: Anything at all separating `<head>` tags, including space or newline, does trip the linter.
<img width="492" alt="consecutive opening and closing head tags with no title attribute, this time with a space between. Linter underline present." src="https://user-images.githubusercontent.com/6492662/50730389-7d44e600-111a-11e9-81dc-a71bec01091d.png">

**Visual Studio Code (please complete the following information):**
 - Version 1.29.1

**Additional context**
This will probably be a pretty rare problem since most devs do make use of the `<header>` space for one thing or another if not `<title>` tags, but it's a fun edge case to put to bed.

**Comment by mvdschee** [comment]
@ecerta Thanks for pointing that out, something I probably overlooked while using autocomplete. I think it's indeed a rare edge case but still, a bug that needs to be squeezed!
